<?php
// Variables
return [
  "creatorName" => "Eeja07",
  "creatorUrl" => "https://miot-its.org",
  "templateName" => "Mivion",
  "templateSuffix" => "",
  "templateVersion" => "2.0.0",
  "templateFree" => false,
  "templateDescription" => "Mivion is an intelligent surveillance platform providing real-time monitoring, telemetry visualization, firmware management, and AI-powered security insights.",
  "templateKeyword" => "Mivion,CCTV,ESP32-CAM,Detection,OTA,Telemetry",
  "licenseUrl" => "",
  "livePreview" => "",
  "productPage" => "",
  "support" => "",
  "moreThemes" => "",
  "documentation" => "",
  "generator" => "",
  "changelog" => "",
  "repository" => "",
  "gitRepo" => "",
  "gitRepoAccess" => "",
  "githubFreeUrl" => "",
  "facebookUrl" => "",
  "twitterUrl" => "",
  "githubUrl" => "",
  "dribbbleUrl" => "",
  "instagramUrl" => "",
  "logoUrl" => "assets/images/logomivio.png",
];
